name: good_wallet
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  stripe_payment: ^1.0.6
  firebase_core: ^1.0.1
  firebase_storage: ^8.0.0
  cloud_firestore: ^1.0.1
  cloud_functions: ^1.0.0

  # Firebase Authentications
  firebase_auth: ^1.0.1 
  google_sign_in: ^4.5.6
  sign_in_with_apple: ^2.5.4
  # flutter_facebook_auth: ^3.1.1

  intl: ^0.17.0
  modal_progress_hud: ^0.1.3
  qr_flutter: ^3.2.0
  #flutter_barcode_scanner: ^1.0.1
  path_provider: ^2.0.1

  # Stacked State Management
  stacked: ^1.9.7
  stacked_services: ^0.6.0
  stacked_firebase_auth: ^0.1.2

  get_it: ^6.0.0
  image_picker: ^0.7.2+1
  cached_network_image: ^2.4.1
  observable_ish: ^2.1.4
  animations: ^1.1.2
  material_floating_search_bar: ^0.2.4
  uuid: ^3.0.0
  flutter_hooks:
  auto_route:
  http: ^0.13.0
  webview_flutter: ^1.0.7
  js: ^0.6.2
  rxdart: ^0.25.0
  flutter_typeahead: 3.0.0-nullsafety.0
  scroll_to_index: ^2.0.0
  universal_html: ^2.0.2
  percent_indicator: ^2.1.9+1
  logger: ^0.9.0  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  auto_route_generator:
  stacked_generator: ^0.2.4    

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/hand-with-heart.jpg
    - assets/images/hand-shake-on-yellow.jpg
    - assets/images/G_icon.png
    - assets/images/vancouver_seawall.jpg
    - assets/images/woman-holding-flower.jpg
    - assets/images/vacuum.png
    - assets/images/wallet_icon.png
    - assets/images/btn_google_signin_light_normal_web.png
    - assets/images/our-vision-graphic.png
    - assets/images/concept-text.png
    - assets/images/hand-throwing-dice-on-yellow-highres.jpg
    - assets/images/hand-throwing-dice-on-yellow.jpg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
